/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/// <summary>
/// Apache Thrift IDL definition for the LisMusic Streaming service
/// </summary>
public enum Quality
{
  HIGH = 0,
  MIDDLE = 1,
  LOW = 2,
}
